name: test

on: push

jobs:
  build:  
    name: Rstats 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable    
    - run: cargo test --release -- --nocapture --color always --test-threads=1
